--Q16--
SELECT EMPLOYEE.Name, SUM(SERVICE.Hours) as Total_Maintenance_Hours
FROM EMPLOYEE
JOIN MAINTAINS ON EMPLOYEE.Ssn = MAINTAINS.Ssn
JOIN SERVICE ON MAINTAINS.ServiceID = SERVICE.ServiceID
JOIN AIRPLANE ON SERVICE.Reg# = AIRPLANE.Reg#
JOIN OWNS ON AIRPLANE.Reg# = OWNS.Reg#
JOIN CORPORATION ON OWNS.Ssn = CORPORATION.Name
WHERE CORPORATION.Name = '123 CORP'
GROUP BY EMPLOYEE.Name
ORDER BY Total_Maintenance_Hours DESC;
